[package]
name = "orbtk_render"
version = "0.3.1-alpha4"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "2D Render library use by OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["2D", "render", "canvas"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4"
smallvec = { version = "1", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = { version = "0.23",  default-features = false, features = ["ico"] }

# raqote depenencies
raqote = { version = "0.8", default-features = false, optional = true }
rusttype = { version = "0.9", optional = true }
smallvec = "1"

# pathfinder dependencies
pathfinder_canvas = { version = "0.5.0", features = ["pf-text"], optional = true }
pathfinder_color = { version = "0.5", optional = true }
pathfinder_content = { version = "0.5", optional = true }
pathfinder_geometry = { version = "0.5", optional = true }
pathfinder_gl = { version = "0.5", optional = true }
pathfinder_gpu =  { version = "0.5", optional = true }
pathfinder_renderer = { version = "0.5", optional = true }
pathfinder_resources =  { version = "0.5", optional = true }
font-kit = { version = "0.10", optional = true }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "redox")))'.dependencies]
skia-safe = { version = "0", features = ["gl"], optional = true }
fnv = { version = "1", optional = true }

[dependencies]
orbtk_utils = { path = "../utils", version = "0.3.1-alpha4" }

[features]
default = ["raqote", "rusttype"]
glupath = [
    "pathfinder_canvas",
    "pathfinder_color",
    "pathfinder_content",
    "pathfinder_geometry",
    "pathfinder_gl",
    "pathfinder_gpu",
    "pathfinder_renderer",
    "pathfinder_resources",
    "font-kit"
]
skia = [
    "skia-safe",
    "fnv"
]