[package]
name = "orbtk-utils"
version = "0.3.1-alpha4"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Helper utils and traits for OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["helpers", "utils", "traits", "ui"]
edition = "2018"

[dependencies]
lexical-core = "0.7"
ron = "0.6"
phf = { version = "0.8", default-features = false }
serde = "1.0"
derive_more = { version = "0.99", default-features = false, features = ["add", "constructor", "from"] }


[build-dependencies]
<<<<<<< HEAD
phf_codegen = { version = "0.8", default-features = false }
=======
phf_codegen = { version = "0.8", default-features = false }
>>>>>>> 2bb30e4b7ea19218982317842e8db54a210db657
